sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t davebulaklak/docker-react-2  -f Dockerfile.dev .

script:
  - docker run -e CI=true davebulaklak/docker-react-2  npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-977936595005"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
